name: hairprint
description: "Hairprint - Your AI Trichologist by The Hair Society."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.0
  http: ^0.13.6
  path: ^1.8.3
  share_plus: ^7.2.1
  http_parser: ^4.0.2
  image: ^4.1.3
  flutter_html: ^3.0.0
  printing: ^5.11.0
  path_provider: ^2.1.2
  pdf: ^3.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
